version: 1.0.0-{build}
configuration: Release
cache:
  - packages -> **\packages.config
before_build:
  nuget restore
build:
  publish_wap: true
deploy:
  provider: Environment
  name: codeshare-appveyor-example
  on:
    appveyor_repo_tag: true
