version: 1.1.0-{build}
configuration: Release
cache:
  - packages -> **\packages.config
before_build:
  nuget restore
build:
publish_wap_xcopy: true
deploy:
- provider: AzureAppServiceZipDeploy
  website: armsacctsasapp
  username: $armsacctsasapp
  password:
    secure: dj4z0cjsQwgP1tQFD5EpR3X82pntGZ1a5Y8r9nDYyubbddLzWAvrhAMSeGPS
